spring:
 application:
    name: cards
 datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: sa
  password: sa
 jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
 h2:
    console:
      enabled: true
 profiles:
    active: prod
 config:
    import: optional:configserver:http://localhost:8071
server:
  port: 8083
  servlet:
    context-path: /cards
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/ 
    
info:
  app:
    name: cards microservice
    description: Cambank cards microservice
    version: 1.0.0
    
management:
  info:
    env:
      enabled: true
  endpoint:
   shutdown:
      enabled: true
   metrics:
    enabled: true
  endpoints:
   web:
    exposure:
     include: 
      - refresh
      - info