loans:
  msg: Welcome to the Cambank Loans Dev application
  build-version: '2'
  mailDetails:
    hostName: dev-loans@eazybytes.com
    port: '9021'
    from: dev-loans@eazybytes.com
    subject: Your Loan Details from Eazy Bank Dev Environment
  activeBranches:
    - Chennai
    - Berlin
    - Indianapollis
