loans:
  msg: Welcome to the Cambank Loans Default application
  build-version: '3'
  mailDetails:
    hostName: default-loans@eazybytes.com
    port: '9001'
    from: default-loans@eazybytes.com
    subject: Your Loan Details from Eazy Bank Default Environment
  activeBranches:
    - Mumbai
    - London
    - Washington
