spring:
  #due to performance reasons, 10% of the logs are going to send to the zipking collector
 sleuth:
    sampler:
      percentage: 1


 #zipkin configuration when it does not use queue strategy to process logs location
 zipkin:
    baseUrl: http://localhost:9411/


 #zipkin configuration when it uses queue strategy to process logs location
# zipkin:
#    sender:
#      type: rabbit
#    rabbitmq:
#      queue: zipking-log-queue


 #Rabbitmq connection info
 rabbitmq:
    password: guest
    port: '5672'
    host: localhost
    username: guest
 application:
    name: accounts
 datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: sa
  password: sa
 jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
 h2:
    console:
      enabled: true
 profiles:
    active: local
 config:
    import: optional:configserver:http://localhost:8071
server:
  port: 8081
#  servlet:
#    context-path: /accounts
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8073/eureka/
info:
  app:
    name: accounts microservice
    description: Cambank accounts microservice
    version: 1.0.0
    
resilience4j:
  circuitbreaker:
    configs:
      default: 
        register-health-indicator: true
    instances:
      customerDetailsCircuitBreaker:
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30000
        permitted-number-of-calls-in-half-open-state: 2
  retry:
    instances:
      retryCustomerDetail:
        max-attempts: 3
        wait-duration: 2000
  ratelimiter:
    configs:
      default:
        register-health-indicator: true
    instances:
      sayHello:
        timeout-duration: 5000
        limit-refresh-period: 5000
        limit-for-period: 1    
management:
  info:
    env:
      enabled: true
  endpoint:
   shutdown:
      enabled: true
   metrics:
    enabled: true
  endpoints:
   web:
    exposure:
     include: 
      - refresh
      - info